#ifndef ERROR_H
#define ERROR_H

// Enum for result codes used throughout the application.
typedef enum {
  ORDO_OK = 0,

  // Erros
  ORDO_ERROR_GENERIC = 1,
  ORDO_ERROR_DATABASE,
  ORDO_ERROR_TASK_NOT_FOUND,
  ORDO_ERROR_EMPTY_DESCRIPTION,
  ORDO_ERROR_INVALID_INPUT,
  ORDO_ERROR_TASK_LIMIT_REACHED,
  ORDO_ERROR_CONFIG_FILE_ERROR,

  // Mensagens de sucesso para a UI
  ORDO_ADD_SUCCESS,
  ORDO_REMOVE_SUCCESS,
  ORDO_EDIT_SUCCESS,
  ORDO_TOGGLE_SUCCESS_DONE,
  ORDO_TOGGLE_SUCCESS_REOPEN,
  ORDO_TRASH_SUCCESS,
  ORDO_RESTORE_SUCCESS,
  ORDO_PERM_DELETE_SUCCESS,

  // Undo/Redo
  ORDO_UNDO_SUCCESS,
  ORDO_UNDO_FAILURE,
  ORDO_REDO_SUCCESS,
  ORDO_REDO_FAILURE,

} OrdoResult;

#endif // ERROR_H